# Spring Boot application properties
# Configuracio general de l'aplicacio
# !! NO POSAR INFORMACIO SENSIBLE EN AQUEST FITXER, NI ACCENTS NI CARACTERES ESPECIALS !!
# !! UTILITZAR VARIABLES D'ENTORN O application-local.properties PER AQUEST TIPUS DE DADES !!

spring.application.name=backend
spring.profiles.active=local

# Configuracio de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Configuracio de l'script de Comissaries ---
# URL de l'API per obtenir el CSV
opendata.comissaries.url=https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=comissaries-policia

# --- Configuracio de l'script de Fonts aigua ---
# URL de l'API per obtenir el CSV
opendata.fonts_beure.url=https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=fonts

# --- Configuracio de l'script de Bancs publics ---
# URL de l'API per obtenir el CSV
opendata.bancs.url=https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=infraestructures-inventari-bancs

# --- Configuracio de l'script de Escales mecaniques ---
# URL de l'API per obtenir el CSV
opendata.escales_mecaniques.url=https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=escales-mecaniques

# --- Configuracio de l'script de Arbrat viari (arbres, situats als carrers)---
# URL de l'API per obtenir el CSV
opendata.arbrat_viari.url=https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=arbrat-viari

# --- Configuracio de l'script de Arbrat zona (arbres, situats en places, parterres, glorietes o petits espais enjardinats)---
# URL de l'API per obtenir el CSV
opendata.arbrat_zona.url=https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=arbrat-zona

# --- Configuracio de l'script de Cameres de seguretat ---
# URL de l'API per obtenir les dades
opendata.cameres.url=https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=infraestructures-inventari-cameres

# --- Configuracio de l'script de Fets Penals (Gencat) ---
# URL per obtenir el CSV (Directe de l'API de Transparencia)
opendata.fets_penals.url=https://analisi.transparenciacatalunya.cat/api/views/qnyt-emjc/rows.csv?accessType=DOWNLOAD

# --- Configuracio de l'script de Fets Delictius i Infraccions (Joc) ---
# URL per obtenir el CSV directe
opendata.infraccions_joc.url=https://analisi.transparenciacatalunya.cat/api/views/y48r-ae59/rows.csv?accessType=DOWNLOAD

# Nom de la taula on es guardaran les dades
db.table.comissaries=bcn_comissaries
db.table.fonts_beure=bcn_fonts_beure
db.table.bancs=bcn_bancs
db.table.escales_mecaniques=bcn_escales_mecaniques
db.table.arbrat_viari=bcn_arbrat_viari
db.table.arbrat_zona=bcn_arbrat_zona
db.table.cameres=bcn_cameres_seguretat
db.table.fets_penals=cat_fets_penals
db.table.infraccions_joc=cat_infraccions_joc