# Spring Boot application properties
# Configuracio general de l'aplicacio
# !! NO POSAR INFORMACIO SENSIBLE EN AQUEST FITXER, NI ACCENTS NI CARACTERES ESPECIALS !!
# !! UTILITZAR VARIABLES D'ENTORN O application-local.properties PER AQUEST TIPUS DE DADES !!

spring.application.name=backend
spring.profiles.active=local

# Configuracio de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true