# Spring Boot application properties
# Configuracio general de l'aplicacio
# !! NO POSAR INFORMACIO SENSIBLE EN AQUEST FITXER, NI ACCENTS NI CARACTERES ESPECIALS !!
# !! UTILITZAR VARIABLES D'ENTORN O application-local.properties PER AQUEST TIPUS DE DADES !!

spring.application.name=backend
spring.profiles.active=local

# Configuracio de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuracio dels scripts d'open data
opendata.grafvial.url=https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=mapa-graf-viari-carrers-wms

# Nom de taules i de vistes a la base de dades
db.table.trams=bcn_grafvial_trams
db.table.nodes=bcn_grafvial_nodes

# Nom de les vistes a la base de dades
db.view.rutes=v_trams_nodes